# Generated by Django 5.2.7 on 2025-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('ANULADA', 'Anulada'), ('COMPLETADA', 'Completada'), ('NO ASISTEN', 'No asisten')], default='RESERVADO', max_length=20),
        ),
    ]
